---
title: "simtests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
```




```{r predict, echo=FALSE}
predict_aapl_1 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_aapl_1.csv")
predict_aapl_1 <- predict_aapl_1 %>% mutate(error = actual-mid, days = 1:365)
predict_aapl_1 %>% summarise(mean(error))
predict_aapl_1 %>% filter(days < 31) %>% summarise(mean(error))
predict_aapl_1 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_aapl_1, aes(x = days, y = error)) + geom_point()
predict_aapl_3 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_aapl_3.csv")
predict_aapl_3 <- predict_aapl_3 %>% mutate(error = actual-mid, days = 1:365)
predict_aapl_3 %>% summarise(mean(error))
predict_aapl_3 %>% filter(days < 31) %>% summarise(mean(error))
predict_aapl_3 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_aapl_3, aes(x = days, y = error)) + geom_point()
predict_aapl_5 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_aapl_5.csv")
predict_aapl_5 <- predict_aapl_5 %>% mutate(error = actual-mid, days = 1:365)
predict_aapl_5 %>% summarise(mean(error))
predict_aapl_5 %>% filter(days < 31) %>% summarise(mean(error))
predict_aapl_5 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_aapl_5, aes(x = days, y = error)) + geom_point()
predict_aapl_7 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_aapl_7.csv")
predict_aapl_7 <- predict_aapl_7 %>% mutate(error = actual-mid, days = 1:365)
predict_aapl_7 %>% summarise(mean(error))
predict_aapl_7 %>% filter(days < 31) %>% summarise(mean(error))
predict_aapl_7 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_aapl_7, aes(x = days, y = error)) + geom_point()
predict_aapl_10 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_aapl_10.csv")
predict_aapl_10 <- predict_aapl_10 %>% mutate(error = actual-mid, days = 1:365)
predict_aapl_10 %>% summarise(mean(error))
predict_aapl_10 %>% filter(days < 31) %>% summarise(mean(error))
predict_aapl_10 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_aapl_10, aes(x = days, y = error)) + geom_point()

predict_cnc_1 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_cnc_1.csv")
predict_cnc_1 <- predict_cnc_1 %>% mutate(error = actual-mid, days = 1:365)
predict_cnc_1 %>% summarise(mean(error))
predict_cnc_1 %>% filter(days < 31) %>% summarise(mean(error))
predict_cnc_1 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_cnc_1, aes(x = days, y = error)) + geom_point()
predict_cnc_3 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_cnc_3.csv")
predict_cnc_3 <- predict_cnc_3 %>% mutate(error = actual-mid, days = 1:365)
predict_cnc_3 %>% summarise(mean(error))
predict_cnc_3 %>% filter(days < 31) %>% summarise(mean(error))
predict_cnc_3 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_cnc_3, aes(x = days, y = error)) + geom_point()
predict_cnc_5 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_cnc_5.csv")
predict_cnc_5 <- predict_cnc_5 %>% mutate(error = actual-mid, days = 1:365)
predict_cnc_5 %>% summarise(mean(error))
predict_cnc_5 %>% filter(days < 31) %>% summarise(mean(error))
predict_cnc_5 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_cnc_5, aes(x = days, y = error)) + geom_point()
predict_cnc_7 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_cnc_7.csv")
predict_cnc_7 <- predict_cnc_7 %>% mutate(error = actual-mid, days = 1:365)
predict_cnc_7 %>% summarise(mean(error))
predict_cnc_7 %>% filter(days < 31) %>% summarise(mean(error))
predict_cnc_7 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_cnc_7, aes(x = days, y = error)) + geom_point()
predict_cnc_10 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_cnc_10.csv")
predict_cnc_10 <- predict_cnc_10 %>% mutate(error = actual-mid, days = 1:365)
predict_cnc_10 %>% summarise(mean(error))
predict_cnc_10 %>% filter(days < 31) %>% summarise(mean(error))
predict_cnc_10 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_cnc_10, aes(x = days, y = error)) + geom_point()

predict_jnp_1 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_jnp_1.csv")
predict_jnp_1 <- predict_jnp_1 %>% mutate(error = actual-mid, days = 1:365)
predict_jnp_1 %>% summarise(mean(error))
predict_jnp_1 %>% filter(days < 31) %>% summarise(mean(error))
predict_jnp_1 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_jnp_1, aes(x = days, y = error)) + geom_point()
predict_jnp_3 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_jnp_3.csv")
predict_jnp_3 <- predict_jnp_3 %>% mutate(error = actual-mid, days = 1:365)
predict_jnp_3 %>% summarise(mean(error))
predict_jnp_3 %>% filter(days < 31) %>% summarise(mean(error))
predict_jnp_3 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_jnp_3, aes(x = days, y = error)) + geom_point()
predict_jnp_5 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_jnp_5.csv")
predict_jnp_5 <- predict_jnp_5 %>% mutate(error = actual-mid, days = 1:365)
predict_jnp_5 %>% summarise(mean(error))
predict_jnp_5 %>% filter(days < 31) %>% summarise(mean(error))
predict_jnp_5 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_jnp_5, aes(x = days, y = error)) + geom_point()
predict_jnp_7 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_jnp_7.csv")
predict_jnp_7 <- predict_jnp_7 %>% mutate(error = actual-mid, days = 1:365)
predict_jnp_7 %>% summarise(mean(error))
predict_jnp_7 %>% filter(days < 31) %>% summarise(mean(error))
predict_jnp_7 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_jnp_7, aes(x = days, y = error)) + geom_point()
predict_jnp_10 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_jnp_10.csv")
predict_jnp_10 <- predict_jnp_10 %>% mutate(error = actual-mid, days = 1:365)
predict_jnp_10 %>% summarise(mean(error))
predict_jnp_10 %>% filter(days < 31) %>% summarise(mean(error))
predict_jnp_10 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_jnp_10, aes(x = days, y = error)) + geom_point()

predict_tsla_1 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_tsla_1.csv")
predict_tsla_1 <- predict_tsla_1 %>% mutate(error = actual-mid, days = 1:365)
predict_tsla_1 %>% summarise(mean(error))
predict_tsla_1 %>% filter(days < 31) %>% summarise(mean(error))
predict_tsla_1 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_tsla_1, aes(x = days, y = error)) + geom_point()
predict_tsla_3 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_tsla_3.csv")
predict_tsla_3 <- predict_tsla_3 %>% mutate(error = actual-mid, days = 1:365)
predict_tsla_3 %>% summarise(mean(error))
predict_tsla_3 %>% filter(days < 31) %>% summarise(mean(error))
predict_tsla_3 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_tsla_3, aes(x = days, y = error)) + geom_point()
predict_tsla_5 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_tsla_5.csv")
predict_tsla_5 <- predict_tsla_5 %>% mutate(error = actual-mid, days = 1:365)
predict_tsla_5 %>% summarise(mean(error))
predict_tsla_5 %>% filter(days < 31) %>% summarise(mean(error))
predict_tsla_5 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_tsla_5, aes(x = days, y = error)) + geom_point()
predict_tsla_7 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_tsla_7.csv")
predict_tsla_7 <- predict_tsla_7 %>% mutate(error = actual-mid, days = 1:365)
predict_tsla_7 %>% summarise(mean(error))
predict_tsla_7 %>% filter(days < 31) %>% summarise(mean(error))
predict_tsla_7 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_tsla_7, aes(x = days, y = error)) + geom_point()
predict_tsla_10 <- read_csv("C:/Users/johnm/Documents/sim_test_data/predict_tsla_10.csv")
predict_tsla_10 <- predict_tsla_10 %>% mutate(error = actual-mid, days = 1:365)
predict_tsla_10 %>% summarise(mean(error))
predict_tsla_10 %>% filter(days < 31) %>% summarise(mean(error))
predict_tsla_10 %>% filter(days < 8) %>% summarise(mean(error))
ggplot(predict_tsla_10, aes(x = days, y = error)) + geom_point()
```